server:
  port: 11001
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#        - id: 163
#          uri: lb://nacos-provide
#          predicates:
#            - Path=/**
#          filters:
#            - name: Hystrix
#              args:
#                name: fallbackcmd
#                fallbackUri: forward:/fallback
#            - name: FallbackHeaders
#              args:
#                executionExceptionTypeHeaderName: Test-Header
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 1
#                key-resolver: "#{@userKeyResolver}"
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    port: 6379
    host: localhost
